services:
  app:
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    build: .
    ports:
      - 8000:8000
    environment:
      POSTGRES_SERVER: postgres
      REDIS_SERVER: redis
      QDRANT_SERVER: qdrant
  worker:
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    build: .
    command: python -m app.workers.worker
    environment:
      POSTGRES_SERVER: postgres
      REDIS_SERVER: redis
      QDRANT_SERVER: qdrant
  postgres:
    networks:
      - app-network
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql
  redis:
    networks:
      - app-network
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  qdrant:
    networks:
      - app-network
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  pg_data:
  redis-data:
  qdrant_data:
networks:
  app-network:
