services:
  web:
    depends_on:
      - backend
    networks:
      - app-network
    build: ./web
    ports:
      - 3000:80
  backend:
    depends_on:
      - postgres
      - redis
      - qdrant
    networks:
      - app-network
    build: ./backend
    ports:
      - 8000:8000
    environment:
      POSTGRES_SERVER: postgres
      REDIS_SERVER: redis
      QDRANT_SERVER: qdrant
    volumes:
      - uploads_files:/appuser/uploads
  worker:
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    build: ./backend
    command: python -m app.workers.worker
    environment:
      POSTGRES_SERVER: postgres
      REDIS_SERVER: redis
      QDRANT_SERVER: qdrant
    volumes:
      - uploads_files:/appuser/uploads
  postgres:
    networks:
      - app-network
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql
  redis:
    networks:
      - app-network
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  qdrant:
    networks:
      - app-network
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  pg_data:
  redis-data:
  qdrant_data:
  uploads_files:
networks:
  app-network:
